name: massai mara park 01 dockerhub build

on:
  workflow_dispatch

jobs:
  mmpark01_dockerhub_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
        
      - name: docker operations
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/massai_mara:v1 .

          docker push ${{secrets.DOCKER_USERNAME}}/massai_mara:v1
      
      - name: logout from docker hub
        if: always()
        run: docker logout

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: run docker container
        run: |
          docker run -d --name mmpark01 -p 8080:8080 massai_mara:v1
          sleep 20

          docker ps
          docker logs mmpark01

      - name: run automated test #1
        run: |
          curl http://localhost:8080

      - name: run automated test #2
        run: |
          curl http://localhost:8080/images

      - name: run automated test #3
        run: |
          curl http://localhost:8080/animal

      