name: massai mara park 01 multiple jobs

on:
  workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: grant execute permission
        run: chmod +x gradlew

      - name: build with gradle
        run: ./gradlew clean build

      - name: list build/libs directory
        run: ls -al ./build/libs

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application.jar
          path: build/libs/massai_mara_park-0.0.1-SNAPSHOT.jar

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: download JAR artifact
        uses: actions/download-artifact@v4
        with: 
          name: application.jar
      
      - name: check download files
        run: ls -al
      
      - name: run springboot application
        run: |
           java -jar ./application.jar & || exit 1
           sleep 30 # stand by 30 sec
  
  test:
    name: test
    needs: deploy
    runs-on: ubuntu-22.04
    steps:
      - name: run automated test #1
        run: |
          curl http://localhost:8080

      - name: run automated test #2
        run: |
          curl http://localhost:8080/images

      - name: run automated test #3
        run: |
          curl http://localhost:8080/animal

      