name: massai mara park 01 compose dockerhub multiplejobs

on:
  workflow_dispatch

env:
  DOCKER_USERNAME: jiyeonyou
  IMAGE_NAME: massai_mara
  IMAGE_TAG: v${{github.run_number}}
  HOSTNAME: "3.35.138.117"
  USER_NAME: ubuntu

jobs:
  build_image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: check image
        run: |
          docker image ls

      - name: save docker image
        run: |
          docker save ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} > image.tar
      
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  hub_push:
    needs: build_image
    runs-on: ubuntu-22.04

    steps:
      - name: download JAR artifact
        uses: actions/download-artifact@v4
        with: 
          name: docker-image

      - name: check downloaded image
        run: ls -al

      - name: load docker image
        run: |
          docker load < image.tar

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          
      - name: docker operations
        run: |
          docker push ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}

          docker tag ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} \
               ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

          docker push ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

          docker search ${{env.IMAGE_NAME}}:latest
      
      - name: logout from docker hub
        if: always()
        run: docker logout

  upload_compose:
    needs: hub_push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: copy file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{env.HOSTNAME}}
          username: ${{env.USER_NAME}}
          key: ${{secrets.EC2_PRIVATEKEY}}
          port: 22
          source: "compose-multijobs.yaml"
          target: "/home/${{env.USERNAME}}"

  run_test:
    needs: hub_push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: copy file to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{env.HOSTNAME}}
          username: ${{env.USER_NAME}}
          key: ${{secrets.EC2_PRIVATEKEY}}
          port: 22
          script: |
            docker compose -f ./compose-multijobs.yaml up -d
            sleep 30
            docker compose ps
            docker compose logs
